#!/bin/csh
#
set os=`uname`
if ($os == AIX) then
   echo This script must be run on Linux with its newer tar command.
   exit 4
endif
#
#   make a compressed tar file (of the ASCII information only)
#
chdir ~mike
#
set echo
mv gamess/install.info          ~/install.info
mv gamess/gamess.127.x          ~/gamess.127.x
mv gamess/gamess.128.x          ~/gamess.128.x
mv gamess/ddikick.x             ~/ddikick.x
mv gamess/ddi/libddi.a          ~/libddi.a
mv gamess/tools/actvte.x        ~/actvte.x
mv gamess/tools/cartic.x        ~/cartic.x
mv gamess/tools/clenmo.x        ~/clenmo.x
mv gamess/tools/mbldr.x         ~/mbldr.x
mv gamess/graphics/dendif.ps.x  ~/dendif.ps.x
mv gamess/graphics/mepmap.ps.x  ~/mepmap.ps.x
mv gamess/graphics/molplt.ps.x  ~/molplt.ps.x
mv gamess/graphics/pltorb.ps.x  ~/pltorb.ps.x
mv gamess/graphics/dendif.xw.x  ~/dendif.xw.x
mv gamess/graphics/mepmap.xw.x  ~/mepmap.xw.x
mv gamess/graphics/molplt.xw.x  ~/molplt.xw.x
mv gamess/graphics/pltorb.xw.x  ~/pltorb.xw.x
mv gamess/object ~/abcxyz-object
#
mkdir gamess/object
tar -cvf ~mike/gamess.tar --exclude .svn   --exclude .hg \
                          --exclude manual --exclude tinker \
                                        gamess
rmdir gamess/object
#
mv install.info  gamess
mv gamess.127.x  gamess
mv gamess.128.x  gamess
mv ddikick.x     gamess/ddikick.x
mv libddi.a      gamess/ddi/libddi.a
mv actvte.x      gamess/tools
mv cartic.x      gamess/tools
mv clenmo.x      gamess/tools
mv mbldr.x       gamess/tools
mv dendif.ps.x   gamess/graphics
mv mepmap.ps.x   gamess/graphics
mv molplt.ps.x   gamess/graphics
mv pltorb.ps.x   gamess/graphics
mv dendif.xw.x   gamess/graphics
mv mepmap.xw.x   gamess/graphics
mv molplt.xw.x   gamess/graphics
mv pltorb.xw.x   gamess/graphics
mv abcxyz-object gamess/object
#
unset echo
echo -n "Should I compress the tar file down? (y/n) "
set squeeze=$<
if ($squeeze == y) then
   ls -lF ~mike/gamess.tar
   gzip   ~mike/gamess.tar
   ls -lF ~mike/gamess.tar.gz
else
   ls -lF ~mike/gamess.tar
endif
exit
