#!/bin/csh
#
#   make a compressed tar file (of the ASCII information only)
#
#   Note that the repository must be called 'gamess' while running this.
#
chdir /u1/mike
set TREE=gamess
#
mv $TREE/object ~/abcxyz-object
mkdir $TREE/object
#
tar -cvf gamess.tar --exclude .git   --exclude .gitignore \
                    --exclude manual --exclude tinker \
                    --exclude '*.x' \
                    --exclude '*.a' \
                    --exclude '*.log' \
                    --exclude tests/comptests   \
                    --exclude tests/excitations \
                    --exclude tests/qmefpea     \
                    --exclude tests/testsets    \
                    --exclude $TREE/Makefile \
                    --exclude $TREE/install.info     $TREE
#
rmdir $TREE/object
mv abcxyz-object $TREE/object
#
echo -n "Should I compress the tar file down? (y/n) "
set squeeze=$<
if ($squeeze == y) then
   ls -lF ~mike/gamess.tar
   gzip   ~mike/gamess.tar
   ls -lF ~mike/gamess.tar.gz
else
   ls -lF ~mike/gamess.tar
endif
exit
