#!/bin/csh
#
#   7 Jan 1992 - MWS - Execute MOLPLT on Unix
#
set JOB=$1
if (null$JOB == null) then
   echo "The syntax to execute MOLPLT is "
   echo "     molplt xxx"
   echo "where xxx is the name of your xxx.mol input file."
   exit
endif
#
if (-e $JOB.mol) then
else
   echo I could not find $JOB.mol in your current directory.
   echo Bombing out...
   exit
endif
#
echo " "
echo "Please enter 'xw' for X-windows output, 'ps' for PostScript."
set OUTPUT=$<
#
setenv MOLPLT $JOB.mol
#
if ($OUTPUT == xw) then
   molplt.xw.x
endif
#
if ($OUTPUT == ps) then
   setenv PSTNAM $JOB.ps
   molplt.ps.x
   echo "Your PostScript image is now in the file $PSTNAM"
   unsetenv PSTNAM
endif
#
unsetenv MOLPLT
exit
