#!/bin/csh
set E0=-3101.411694206329

set E=`grep "ELONGATION RHF TOTAL ENERGY" $1 | tail -1 | awk '{ print $5 }'`0
set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1 
echo -n "Eerr=$Eerr. "
exit $ierr 
