#!/bin/csh
set E0=-1671.9642723725

set E=`grep "FINAL UHF ENERGY" $1 | tail -1 | awk '{ print $5 }'`0
set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1 
echo -n "Eerr=$Eerr. "
exit $ierr 
