#!/bin/csh

set E0=-74.6801711720

set E=`grep "TOTAL ENERGY =" $1 | awk '{print $4}'`0
set ierr=0
set error=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1
echo -n "Eerr=$Eerr. "
exit $ierr
