#!/bin/ksh

float rhf0=-760.251760
float mp20=-762.157465

float rhf=`grep "E_RHF            =" $1 | tail -n 1 | awk '{print $3}'`
float mp2=`grep "E_CIM-MP2        =" $1 | tail -n 1 | awk '{print $3}'`

float tolE0=$tolE

integer error=0

#rhf reference
float diffr=$(( "$rhf"-"$rhf0" ))
if (( abs($diffr) > $tolE0 ));
then
	((error++))
fi
#cim-mp2
float diffm=$(( "$mp2"-"$mp20" ))
if (( abs($diffm) > $tolE0 ));
then
	((error++))
fi

printf "RHF=%12.8f; CIM-MP2=%12.8f\n" $diffr $diffm
exit $error
