#!/bin/ksh

float solute0=-413.0848430709
float fgpol0=-1.0191549944
float qmpol0=-0.0295703213

float solute=`grep "SOLUTE ENERGY =" $1 | tail -n 1 | awk '{print $4}'`
float fgpol=`grep "FRAGMENT INDUCTION ENERGY =" $1 | tail -n 1 | awk '{print $5}'`
float qmpol=`grep "SOLUTE INDUCTION ENERGY =" $1 | tail -n 1 | awk '{print $5}'`

float tolE0=$tolE

integer error=0

#solute induction
float diffs=$(( "$solute"-"$solute0" ))
if (( abs($diffs) > $tolE0 ));
then
	((error++))
fi
#fragment induction
float difff=$(( "$fgpol"-"$fgpol0" ))
if (( abs($difff) > $tolE0 ));
then
	((error++))
fi
#qm induction
float diffq=$(( "$qmpol"-"$qmpol0" ))
if (( abs($diffq) > $tolE0 ));
then
	((error++))
fi

printf "Solute=%12.8f; EFind=%12.8f; QMind=%12.8f\n" $diffs $difff $diffq
exit $error
