#!/bin/csh
#
# This compvb file can be altered to help you compile GAMESS/VB2000,
# particularly if you are also using the stand-alone version. It copies 
# the source files from the VB2000 stand-alone directory tree, defined
# by $VB2000PATH, to the GAMESS directory tree, so you only need to make
# alterations to the former. Remove the "#" from the two "cp" lines to
# do this.
#
# Note that this script assumes that the executable number will be the only 
# variable on the call of this script, otherwise it will create gamess.00.x.
#
# You need to move it back one directory to the $GMSPATH directory
# before using it.
#
#cp $VB2000PATH/SRC/vb2000.src vb2000/SRC
#cp $VB2000PATH/SRC/vb2gms.src vb2000/SRC
set VERNO=$1
if (null$VERNO == null) set VERNO=00
./comp vb2000
./comp vb2gms
rm -f gamess.$VERNO.x
./lked gamess $VERNO

