#!/bin/csh

# Utility to extract GAMESS/FMO sparse cube data from GAMESS punch files for 
# RUNTYP=FMO0
# version 1.0, 6.12.04
# Dmitri G. Fedorov
#    AIST, Japan
#
# Usage: 
# grabfmo0 file
# where file.dat* are input
#       file.scube will be output
#
 
if($# < 1) exit 1

foreach i (`ls $1.dat*`)
  echo Processing $i
  grabcube $i
end
cat $1.*.scube >$1.0scube
rm -f $1.*.scube
mv $1.0scube $1.0.scube
