#!/bin/csh

grabcube $1.dat
foreach i (1 2 3 0)
  if(-e $1.$i.scube) then
    scubecon <$1.$i.scube >$1.$i.cube
  endif
end
if(-e $1.1.cube && -e $1.2.cube ) then
  cubediff $1.2.cube $1.1.cube >$1.2-1.cube
endif
