#!/bin/csh
set E0=-232.012879752
set G0=0.0233325

set E=`grep "cule: Euncorr(2)=" $1 | awk '{ print $7 }'`0
set G=`tac $1 | grep -m1 "MAXIMUM GRADIENT" | awk '{ print $4 }'`
set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1 
set Gerr=`$chkabs $G $G0 $tolG`
if($status != 0) set ierr=1
echo -n "Eerr=$Eerr Gerr=$Gerr. "
exit $ierr 
