#!/bin/csh
#
#  Execute MBLDR
#
set JOB=$1
#
if (null$JOB == null) then
   echo " "
   echo The syntax to execute MBLDR is
   echo "     mbldr XXX"
   echo where XXX is the name of your XXX.mb input file.
   echo " "
   echo " "
   exit
endif
#
if (-e $JOB.mb) then
else
   echo I could not find $JOB.mb in your current directory.
   echo Bombing out...
   exit
endif
#
setenv MBLDR  $JOB.mb
#
mbldr.x  >& $JOB.lis
echo Your MBLDR output is now in the file $JOB.lis
#
unsetenv MBLDR
exit
