#!/bin/csh
set VBE0=-76.0293506
set VBD0=2.4353
set ROH0=0.9748
set RHH0=1.5777

set VBE=`grep NSERCH $1 | tail -1 | awk '{ print $4 }'`0
set nVBD=0`grep -n DEBYE $1 | tail -1 | cut -d: -f1 | awk '{ print $1+1 }'`
set VBD=`sed -n -e "$nVBD p" $1 | awk '{ print $4 }'`
set nROH=0`grep -n INTERNUCLEAR $1 | tail -1 | cut -d: -f1 | awk '{ print $1+7 }'`
set ROH=`sed -n -e "$nROH p" $1 | awk '{ print $3 }'`
set nRHH=0`grep -n INTERNUCLEAR $1 | tail -1 | cut -d: -f1 | awk '{ print $1+7 }'`
set RHH=`sed -n -e "$nRHH p" $1 | awk '{ print $5 }'`

set ierr=0
set VBEerr=`$chkabs $VBE $VBE0 $tolE`
if($status != 0) set ierr=1 
set VBDerr=`$chkabs $VBD $VBD0 $tolD`
if($status != 0) set ierr=1
set ROHerr=`$chkabs $ROH $ROH0 $tolR`
if($status != 0) set ierr=1
set RHHerr=`$chkabs $RHH $RHH0 $tolR`
if($status != 0) set ierr=1
echo -n "VBEerr=$VBEerr VBDerr=$VBDerr ROHerr=$ROHerr RHHerr=$RHHerr."
exit $ierr 
