#!/bin/csh
#The 1st of each pair below is the earlier basis that has only on d on S
# and with cartesions. The 2nd line of each pair is spherical harmonics
# for the MO, but cartesians for the VB.
#set MOE0=-436.5240951555
set MOE0=-436.5273999626
#set VBE0=-436.55636760
set VBE0=-436.55972538
#set MOD0=2.3205
set MOD0=2.28164
#set VBD0=1.7999
set VBD0=1.7685

set MOE=`grep "FINAL RHF" $1 | awk '{ print $5 }'`0
set VBE=`grep "DIFF OF MACRO" $1 | tail -1 | awk '{ print $8 }'`0
set nMOD=0`grep -n DEBYE $1 | head -1 | cut -d: -f1 | awk '{ print $1+1 }'`
set MOD=`sed -n -e "$nMOD p" $1 | awk '{ print $4 }'`
set nVBD=0`grep -n DEBYE $1 | tail -1 | cut -d: -f1 | awk '{ print $1+1 }'`
set VBD=`sed -n -e "$nVBD p" $1 | awk '{ print $4 }'`

set ierr=0
set MOEerr=`$chkabs $MOE $MOE0 $tolE`
if($status != 0) set ierr=1 
set VBEerr=`$chkabs $VBE $VBE0 $tolE`
if($status != 0) set ierr=1 
set MODerr=`$chkabs $MOD $MOD0 $tolD`
if($status != 0) set ierr=1
set VBDerr=`$chkabs $VBD $VBD0 $tolD`
if($status != 0) set ierr=1
echo -n "MOEerr=$MOEerr VBEerr=$VBEerr MODerr=$MODerr VBDerr=$VBDerr."
exit $ierr 
