#!/bin/csh
set MOE0=-154.8285407061
set VBE0=-154.86929401
set VBD0=0.0000
set SD0=-0.33638

set MOE=`grep "FINAL ROHF" $1 | awk '{ print $5 }'`0
set VBE=`grep "DIFF OF MACRO" $1 | tail -1 | awk '{ print $8 }'`0
set nVBD=0`grep -n DEBYE $1 | tail -1 | cut -d: -f1 | awk '{ print $1+1 }'`
set VBD=`sed -n -e "$nVBD p" $1 | awk '{ print $4 }'`
set nSD=0`grep -n "SPIN DENSITY ON ATOMS" $1 | cut -d: -f1 | awk '{ print $1+4 }'`
set SD=`sed -n -e "$nSD p" $1 | awk '{ print $2 }'`

set ierr=0
set MOEerr=`$chkabs $MOE $MOE0 $tolE`
if($status != 0) set ierr=1 
set VBEerr=`$chkabs $VBE $VBE0 $tolE`
if($status != 0) set ierr=1 
set VBDerr=`$chkabs $VBD $VBD0 $tolD`
if($status != 0) set ierr=1
set SDerr=`$chkabs $SD $SD0 $tolSD`
if($status != 0) set ierr=1
echo -n "MOEerr=$MOEerr VBEerr=$VBEerr VBDerr=$VBDerr SDerr=$SDerr."
exit $ierr 
