#!/bin/csh
set VBE0=-74.87484148 
set VBD0=0.0000

# Checks very last VB energy and zero dipole at that last point.
set VBE=`grep "DIFF OF MACRO" $1 | tail -1 | awk '{ print $8 }'`0
set nVBD=0`grep -n DEBYE $1 | tail -1 | cut -d: -f1 | awk '{ print $1+1 }'`
set VBD=`sed -n -e "$nVBD p" $1 | awk '{ print $4 }'`

set ierr=0
set VBEerr=`$chkabs $VBE $VBE0 $tolE`
if($status != 0) set ierr=1 
set VBDerr=`$chkabs $VBD $VBD0 $tolD`
if($status != 0) set ierr=1
echo -n "VBEerr=$VBEerr VBDerr=$VBDerr."
exit $ierr 
