#!/bin/csh
set CH0="command"

echo 'VBTYP=VB2000 present, but no $VB2000 block or command line'
set CH=`grep "no command line" $1 | awk '{ print $3 }'`

set ierr=0
if($CH0 != $CH) set ierr=1 
exit $ierr 

