#!/bin/csh
set VBE0=-76.0690435829
set ROH0=0.9678
set ANG0=102.7

set VBE=`grep "TRUDGE ENERGY" $1 | tail -1 | awk '{ print $8 }'`0
set nROH=0`grep -n "INTERNAL COORDINATES" $1 | tail -1 | cut -d: -f1 | awk '{ print $1+4 }'`
set ROH=`sed -n -e "$nROH p" $1 | awk '{ print $2 }'`
set nANG=0`grep -n "INTERNAL COORDINATES" $1 | tail -1 | cut -d: -f1 | awk '{ print $1+4 }'`
set ANG=`sed -n -e "$nANG p" $1 | awk '{ print $3 }'`

set ierr=0
set VBEerr=`$chkabs $VBE $VBE0 $tolE`
if($status != 0) set ierr=1 
set ROHerr=`$chkabs $ROH $ROH0 $tolR`
if($status != 0) set ierr=1
set ANGerr=`$chkabs $ANG $ANG0 $tolW`
if($status != 0) set ierr=1
echo -n "VBEerr=$VBEerr ROHerr=$ROHerr ANGerr=$ANGerr."
exit $ierr 
