#!/bin/csh
set MOE0=-230.1300205664
set VBE0=-229.99812644

set MOE=`grep "FINAL RHF" $1 | awk '{ print $5 }'`0
set VBE=`grep "DIFF OF MACRO" $1 | tail -1 | awk '{ print $8 }'`0

set ierr=0
set MOEerr=`$chkabs $MOE $MOE0 $tolE`
if($status != 0) set ierr=1 
set VBEerr=`$chkabs $VBE $VBE0 $tolE`
if($status != 0) set ierr=1 
echo -n "MOEerr=$MOEerr VBEerr=$VBEerr."
exit $ierr 
