#!/bin/csh
set MOE0=-10.2742272739
set VBE0=-10.31300169
set MOD0=1.48865
set VBD0=1.4404

set MOE=`grep "FINAL RHF" $1 | awk '{ print $5 }'`0
set VBE=`grep "DIFF OF MACRO" $1 | tail -1 | awk '{ print $8 }'`0
set nMOD=0`grep -n DEBYE $1 | head -1 | cut -d: -f1 | awk '{ print $1+1 }'`
set MOD=`sed -n -e "$nMOD p" $1 | awk '{ print $4 }'`
set nVBD=0`grep -n DEBYE $1 | tail -1 | cut -d: -f1 | awk '{ print $1+1 }'`
set VBD=`sed -n -e "$nVBD p" $1 | awk '{ print $4 }'`

set ierr=0
set MOEerr=`$chkabs $MOE $MOE0 $tolE`
if($status != 0) set ierr=1 
set VBEerr=`$chkabs $VBE $VBE0 $tolE`
if($status != 0) set ierr=1 
set MODerr=`$chkabs $MOD $MOD0 $tolD`
if($status != 0) set ierr=1
set VBDerr=`$chkabs $VBD $VBD0 $tolD`
if($status != 0) set ierr=1
echo -n "MOEerr=$MOEerr VBEerr=$VBEerr MODerr=$MODerr VBDerr=$VBDerr."
exit $ierr 
