#!/bin/csh
set VBE0=-76.05312010
set VBD0=2.1132
set ED0=290.3666
set EP0=-23.421387
set EF0=0.134587

# Take first number in each of electron density, electrostatic
# potential and electric field.
set VBE=`grep "DIFF OF MACRO" $1 | tail -1 | awk '{ print $8 }'`0
set nVBD=0`grep -n DEBYE $1 | tail -1 | cut -d: -f1 | awk '{ print $1+1 }'`
set VBD=`sed -n -e "$nVBD p" $1 | awk '{ print $4 }'`
set nED=0`grep -n "ELECTRON DENSITY" $1 | tail -1 | cut -d: -f1 | awk '{ print $1+4 }'`
set ED=`sed -n -e "$nED p" $1 | awk '{ print $5 }'`
set nEP=0`grep -n "ELECTROSTATIC POTENTIAL" $1 | tail -1 | cut -d: -f1 | awk '{ print $1+7 }'`
set EP=`sed -n -e "$nEP p" $1 | awk '{ print $5 }'`
set nEF=0`grep -n "ELECTRIC FIELD" $1 | tail -1 | cut -d: -f1 | awk '{ print $1+8 }'`
set EF=`sed -n -e "$nEF p" $1 | awk '{ print $4 }'`

set ierr=0
set VBEerr=`$chkabs $VBE $VBE0 $tolE`
if($status != 0) set ierr=1 
set VBDerr=`$chkabs $VBD $VBD0 $tolD`
if($status != 0) set ierr=1
set EDerr=`$chkabs $ED $ED0 $tolD`
if($status != 0) set ierr=1
set EPerr=`$chkabs $EP $EP0 $tolD`
if($status != 0) set ierr=1
set EFerr=`$chkabs $EF $EF0 $tolD`
if($status != 0) set ierr=1
echo -n "VBEerr=$VBEerr VBDerr=$VBDerr EDerr=$EDerr EPerr=$EPerr EFerr=$EFerr. "
exit $ierr 
