#!/bin/csh
set E0=-76.02933220
set W10=1717.28
set W20=3587.64
set W30=3734.66

set E=`grep "DIFF OF MACRO" $1 | tail -1 | awk '{ print $8 }'`0
set W1=`grep "FREQUENCY:" $1 | tail -1 | awk '{ print $3 }'`0
set W2=`grep "FREQUENCY:" $1 | tail -1 | awk '{ print $4 }'`0
set W3=`grep "FREQUENCY:" $1 | tail -1 | awk '{ print $5 }'`0

set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1 
set W1err=`$chkabs $W1 $W10 $tolW`
if($status != 0) set ierr=1
set W2err=`$chkabs $W2 $W20 $tolW`
if($status != 0) set ierr=1
set W3err=`$chkabs $W3 $W30 $tolW`
if($status != 0) set ierr=1
echo -n "Eerr=$Eerr W1err=$W1err W2err=$W2err W3err=$W3err. "
exit $ierr 
