#!/bin/csh
set MOE0=-100.4222525464
set VBE0=-100.46902056
set VBD0=0.0000
set SD0=0.56737
set ED0=0.30143
set EP0=-5.23010
set EF0=0.037965

set MOE=`grep "FINAL ROHF" $1 | awk '{ print $5 }'`0
set VBE=`grep "DIFF OF MACRO" $1 | tail -1 | awk '{ print $8 }'`0
set nVBD=0`grep -n DEBYE $1 | tail -1 | cut -d: -f1 | awk '{ print $1+1 }'`
set VBD=`sed -n -e "$nVBD p" $1 | awk '{ print $4 }'`
set nSD=0`grep -n "SPIN DENSITY ON ATOMS" $1 | cut -d: -f1 | awk '{ print $1+4 }'`
set SD=`sed -n -e "$nSD p" $1 | awk '{ print $2 }'`
set nED=0`grep -n "ELECTRON DENSITY" $1 | tail -1 | cut -d: -f1 | awk '{ print $1+4 }'`
set ED=`sed -n -e "$nED p" $1 | awk '{ print $5 }'`
set nEP=0`grep -n "ELECTROSTATIC POTENTIAL" $1 | tail -1 | cut -d: -f1 | awk '{ print $1+7 }'`
set EP=`sed -n -e "$nEP p" $1 | awk '{ print $5 }'`
set nEF=0`grep -n "ELECTRIC FIELD" $1 | tail -1 | cut -d: -f1 | awk '{ print $1+8 }'`
set EF=`sed -n -e "$nEF p" $1 | awk '{ print $4 }'`

set ierr=0
set MOEerr=`$chkabs $MOE $MOE0 $tolE`
if($status != 0) set ierr=1 
set VBEerr=`$chkabs $VBE $VBE0 $tolE`
if($status != 0) set ierr=1 
set VBDerr=`$chkabs $VBD $VBD0 $tolD`
if($status != 0) set ierr=1
set SDerr=`$chkabs $SD $SD0 $tolSD`
if($status != 0) set ierr=1
set EDerr=`$chkabs $ED $ED0 $tolD`
if($status != 0) set ierr=1
set EPerr=`$chkabs $EP $EP0 $tolD`
if($status != 0) set ierr=1
set EFerr=`$chkabs $EF $EF0 $tolD`
if($status != 0) set ierr=1
echo -n "MOEerr=$MOEerr VBEerr=$VBEerr VBDerr=$VBDerr SDerr=$SDerr "
echo -n "EDerr=$EDerr EPerr=$EPerr EFerr=$EFerr. "
exit $ierr 

