#!/bin/csh
set E0=-74.9630286444
set D0=1.725288

set E=`grep "FINAL RHF" $1 | awk '{ print $5 }'`1
set nD=0`grep -n DEBYE $1 | cut -d: -f1 | awk '{ print $1+1 }'`
set D=`sed -n -e "$nD p" $1 | awk '{ print $4 }'`

set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1 
set Derr=`$chkabs $D $D0 $tolD`
if($status != 0) set ierr=1
echo -n "Eerr=$Eerr Derr=$Derr. "
exit $ierr 
