#!/bin/csh
set E0=-224.910612407
set G0=0.0267805

set E=`grep "cule: Euncorr(2)=" $1 | awk '{ print $7 }'`0
set G=`grep "(2) MAXIMUM GRADIENT" $1 | awk '{ print $9 }'`0
set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1 
set Gerr=`$chkabs $G $G0 $tolG`
if($status != 0) set ierr=1
echo -n "Eerr=$Eerr Gerr=$Gerr. "
exit $ierr 
