#!/bin/csh
set E10=-38.941516
set E20=-38.941513
set RMSeg0=0.000005
set tol40=0.000001

#  check the two final energies, and the gradient perp. to seam.

set E1=`grep -i "energy of first state" $1 | tail -1 | awk '{ print $6 }'`
set E2=`grep -i "energy of second state" $1 | tail -1 | awk '{ print $6 }'`
set RMSeg=`grep -i "rms effective gradient" $1 | tail -1 | awk '{ print $5 }'`

set ierr=0
set E1err=`$chkabs $E1 $E10 $tol40`
if($status != 0) set ierr=1
set E2err=`$chkabs $E2 $E20 $tol40`
if($status != 0) set ierr=1
set RMSerr=`$chkabs $RMSeg $RMSeg0 $tol40`
if($status != 0) set ierr=1
echo -n "E1err=$E1err E2err=$E2err RMSerr=$RMSerr"
exit $ierr 
