#!/bin/csh
set E0=-77.9753563843
set W0=319.87
set I0=1.09748

set E=`grep "FINAL MCSCF" $1 | awk '{ print $5 }'`0
set W=`grep "FREQUENCY:" $1 | head -2 | tail -1 | awk '{ print $4 }'`0
set I=`grep "IR INTENSITY:" $1 | head -2 | tail -1 | awk '{ print $5 }'`0
set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1 
set Werr=`$chkabs $W $W0 $tolW`
if($status != 0) set ierr=1
set Ierr=`$chkabs $I $I0 $tolI`
if($status != 0) set ierr=1
echo -n "Eerr=$Eerr Werr=$Werr Ierr=$Ierr. "
exit $ierr 
