#!/bin/csh
set EB10=-55.7479225350
set EA10=-55.6678983648

set EB1=`grep "CCSD ENERGY:" $1 | awk '{ print $3 }'`0
set EA1=`grep "EOMCCSD ENERGY=" $1 | tail -1 | awk '{ print $3 }'`
set ierr=0
set B1err=`$chkabs $EB1 $EB10 $tolE`
if($status != 0) set ierr=1 
set A1err=`$chkabs $EA1 $EA10 $tolE`
if($status != 0) set ierr=1 
echo -n "B1err=$B1err A1err=$A1err. "
exit $ierr 
