#!/bin/csh
set E1S0=-459.7391880598
set E2P0=-459.6170161644

set E1S=`grep "CCSD ENERGY:" $1 | awk '{ print $3 }'`0
set E2P=`grep "IP-EOMCCSDt E=" $1 | tail -1 | awk '{ print $3 }'`
set ierr=0
set Serr=`$chkabs $E1S $E1S0 $tolE`
if($status != 0) set ierr=1 
set Perr=`$chkabs $E2P $E2P0 $tolE`
if($status != 0) set ierr=1 
echo -n "Serr=$Serr Perr=$Perr. "
exit $ierr 
