#!/bin/csh
set E0=-11.3010023066
set X0=0.036713

set E=`grep "FINAL RHF" $1 | tail -1 | awk '{ print $5 }'`0
set X=`grep "P(1)=" $1 | tail -1 | tr -d "," | awk '{ print $2 }'`0
set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1 
set Xerr=`$chkabs $X $X0 $tolX`
if($status != 0) set ierr=1
echo -n "Eerr=$Eerr Xerr=$Xerr. "
exit $ierr 
