#!/bin/csh
set E0=-229.3943496933

set E=`grep "E(MP2)=" $1 | tail -1 | awk '{ print $2 }'`0
set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1 
echo -n "Eerr=$Eerr. "
exit $ierr 
