#!/bin/csh
set HEAT0=-17.83
set tol=0.01

set HEAT=`grep "HEAT OF FORMATION (298K)" $1 | tail -1 | awk '{ print $5 }'`0

set ierr=0
set HEATerr=`$chkabs $HEAT $HEAT0 $tol`
if($status != 0) set ierr=1
echo -n "HEATerr=$HEATerr kcal/mol. "
exit $ierr 
