#!/bin/csh
set E0=-75.7109705643
#--set C0=98.4

#   to test Tokyo program, use 5 instead of 12 in next line, and use comments
set E=`grep "E(MP2)" $1 | tail -1 | awk '{ print $12 }'`0
#--set nC=0`grep -n "REFERENCE WEIGHT" $1 | cut -d: -f1 | awk '{ print $1+3 }'`
#--set C=`sed -n -e "$nC p" $1 | awk '{ print $1 }'`

set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1 
#--set Cerr=`$chkabs $C $C0 $tolC`
#--if($status != 0) set ierr=1
#--echo -n "Eerr=$Eerr Cerr=$Cerr. "
echo -n "Eerr=$Eerr. "
exit $ierr 
