#!/bin/csh
set E0=-91.5814775
set R0=0.89968
set tolE0=0.000001
# customise energy tolerance for DRC

set E=`grep "TOTAL ENERGY" $1 | tail -1 | awk '{ print $4 }'`0
set R=`grep "PATH DISTANCE" $1 | tail -1 | awk '{ print $6 }'`0
set ierr=0
set Eerr=`$chkabs $E $E0 $tolE0`
if($status != 0) set ierr=1 
set Rerr=`$chkabs $R $R0 $tolR`
if($status != 0) set ierr=1
echo -n "Eerr=$Eerr Rerr=$Rerr. "
exit $ierr 
