#!/bin/csh
set E0=-38.8539785232
set B10=1.796
set A10=4.839
set tenm3=0.001

set E=`grep "CR-EOMCC(2,3) OR CR-EOMCCSD(T)_L E=" $1 | tail -1 | awk '{ print $5 }'`0
set nB1=`grep -n "SUMMARY OF CR-EOMCC(2,3) RESULTS FOR ALL STATES" $1 | tail -1 | cut -d: -f1 | awk '{ print $1+4 }'`
@ nA1 = $nB1 + 1
set B1=`sed -n -e "$nB1 p" $1 | awk '{ print $3 }'`
set A1=`sed -n -e "$nA1 p" $1 | awk '{ print $3 }'`
set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1 
set B1err=`$chkabs $B1 $B10 $tenm3`
if($status != 0) set ierr=1 
set A1err=`$chkabs $A1 $A10 $tenm3`
if($status != 0) set ierr=1 
echo -n "Eerr=$Eerr B1err=$B1err A1err=$A1err. "
exit $ierr 
