#!/bin/csh
set E0=-12.6956518722
set W0=913.17

set E=`grep "FINAL RHF" $1 | awk '{ print $5 }'`0
set W=`grep "FREQUENCY:" $1 | tail -1 | awk '{ print $2 }'`0
set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1 
set Werr=`$chkabs $W $W0 $tolW`
if($status != 0) set ierr=1
echo -n "Eerr=$Eerr Werr=$Werr. "
exit $ierr 
