#!/bin/csh
set E0=-76.0440311075
set G0=-0.043055
set D0=-1.296492

set E=`grep "FINAL RHF" $1 | tail -1 | awk '{ print $5 }'`0
set nG=0`grep -n EFGZZ $1 | tail -1 | cut -d: -f1 | awk '{ print $1+1 }'`
set G=`sed -n -e "$nG p" $1 | awk '{ print $3 }'`
set nD=0`grep -n ESU-CM $1 | cut -d: -f1 | awk '{ print $1+1 }'`
set D=`sed -n -e"$nD p" $1 | awk '{ print $3 }'`

set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1 
set Gerr=`$chkabs $G $G0 $tolG`
if($status != 0) set ierr=1
set Derr=`$chkabs $D $D0 $tolD`
if($status != 0) set ierr=1
echo -n "Eerr=$Eerr Gerr=$Gerr Derr=$Derr. "
exit $ierr 
