#!/bin/csh
set E0=-37.2810867259
set G0=0.027589766
set S0=2.013
set La0=30.57
set Lb0=25.14

set E=`grep "FINAL UHF" $1 | awk '{ print $5 }'`0
set G=`grep "RMS G" $1 | awk '{ print $4 }'`0
set S=`grep "S-SQUARED" $1 | awk '{ print $3 }'`0
set La=`grep "FINAL LOC" $1 | head -1 | awk '{ print $6 }'`0
set Lb=`grep "FINAL LOC" $1 | tail -1 | awk '{ print $6 }'`0
set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1 
set Gerr=`$chkabs $G $G0 $tolG`
if($status != 0) set ierr=1
set Serr=`$chkabs $S $S0 $tolS`
if($status != 0) set ierr=1
set Laerr=`$chkabs $La $La0 $tolL`
if($status != 0) set ierr=1
set Lberr=`$chkabs $Lb $Lb0 $tolL`
if($status != 0) set ierr=1
echo -n "Eerr=$Eerr Gerr=$Gerr Serr=$Serr Lerr=$Laerr+$Lberr. "
exit $ierr 
