#!/bin/csh
set E0=-93.0223942017
set G0=0.045100935

set E=`grep "FINAL MCSCF" $1 | awk '{ print $5 }'`0
set G=`grep "RMS G" $1 | head -1 | awk '{ print $4 }'`0
set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1 
set Gerr=`$chkabs $G $G0 $tolG`
if($status != 0) set ierr=1
echo -n "Eerr=$Eerr Gerr=$Gerr. "
exit $ierr 
