#!/bin/csh
set E0=-130.1517479953
set T0=0.01448788

set E=`grep "CR-CCSD(T)_L ENERGY:" $1 | awk '{ print $5 }'`0
set T=`grep "T1 DIAGNOSTIC" $1 | awk '{ print $4 }'`0
set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1 
set Terr=`$chkabs $T $T0 $tolT`
if($status != 0) set ierr=1 
echo -n "Eerr=$Eerr Terr=$Terr. "
exit $ierr 
