#!/bin/csh
set E0=-115.0425622162
set G0=0.0000033
set I0=-0.0079213676

set E=`grep "FINAL RHF" $1 | tail -1 | awk '{ print $5 }'`0
set G=`grep "RMS G" $1 | tail -1 | awk '{ print $8 }'`0
set I=`grep "TOTAL INTERACTION (DELTA" $1 | tail -1 | awk '{ print $13 }'`0
set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1 
set Gerr=`$chkabs $G $G0 $tolG`
if($status != 0) set ierr=1
set Ierr=`$chkabs $I $I0 $tolE`
if($status != 0) set ierr=1
echo -n "Eerr=$Eerr Gerr=$Gerr Ierr=$Ierr. "
exit $ierr 
