#!/bin/csh
set RI0=122.21
set HRI0=976.50
set Itol=0.01

#  check only the non-degenerate mode at 3186.7, 8 lines after titles

set nR=`grep -n "Raman Intensity at omega" $1 | head -1 | cut -d: -f1`
@ nR = $nR + 8
set RI=`sed -n -e "$nR p" $1 | awk '{ print $3 }'`

set nR=`grep -n "Hyper Raman Intensity at omega" $1 | cut -d: -f1`
@ nR = $nR + 8
set HRI=`sed -n -e "$nR p" $1 | awk '{ print $3 }'`

set ierr=0
set RIerr=`$chkabs $RI $RI0 $Itol`
if($status != 0) set ierr=1
set HRIerr=`$chkabs $HRI $HRI0 $Itol`
if($status != 0) set ierr=1
echo -n "RIerr=$RIerr HRIerr=$HRIerr. "
exit $ierr 
