#!/bin/csh
set H0=-2.79646
set G0=0.0000187

set H=`grep "HEAT OF FORM" $1 | tail -1 | awk '{ print $5 }'`0
set G=`grep "RMS G" $1 | tail -1 | awk '{ print $8 }'`0
set ierr=0
set Herr=`$chkabs $H $H0 $tolH`
if($status != 0) set ierr=1 
set Gerr=`$chkabs $G $G0 $tolG`
if($status != 0) set ierr=1
echo -n "Herr=$Herr Gerr=$Gerr. "
exit $ierr 
