#!/bin/csh
set E0=-38.313003683
set G0=0.032264079
set D0=0.691104

set E=`grep "STATE #    2" $1 | awk '{ print $6 }'`0
set G=`grep "RMS G" $1 | awk '{ print $4 }'`0
set nD=0`grep -n DEBYE $1 | tail -1 | cut -d: -f1 | awk '{ print $1+1 }'`
set D=`sed -n -e "$nD p" $1 | awk '{ print $4 }'`

set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1 
set Gerr=`$chkabs $G $G0 $tolG`
if($status != 0) set ierr=1
set Derr=`$chkabs $D $D0 $tolD`
if($status != 0) set ierr=1
echo -n "Eerr=$Eerr Gerr=$Gerr Derr=$Derr. "
exit $ierr 
