#!/bin/csh
set E0=-76.5841347569
set G0=0.0000007

set E=`grep "FINAL R-SVWN" $1 | tail -1 | awk '{ print $5 }'`0
set G=`grep "RMS G" $1 | tail -1 | awk '{ print $8 }'`0
set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1 
set Gerr=`$chkabs $G $G0 $tolG`
if($status != 0) set ierr=1
echo -n "Eerr=$Eerr Gerr=$Gerr. "
exit $ierr 
