#!/bin/csh
set E0=-74.9666740766
set G0=0.033467686
set D0=-0.03663

set E=`grep "FINAL RHF" $1 | awk '{ print $5 }'`0
set G=`grep "RMS G" $1 | awk '{ print $4 }'`0
set D=`grep "Z(IND)" $1 | awk '{ print $3 }'`0
set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1 
set Gerr=`$chkabs $G $G0 $tolG`
if($status != 0) set ierr=1
set Derr=`$chkabs $D $D0 $tolD`
if($status != 0) set ierr=1
echo -n "Eerr=$Eerr Gerr=$Gerr Derr=$Derr. "
exit $ierr 
