#!/bin/csh
set E0=-9.12710
set V0=0.028857623667
set tolE0=0.0001
# customise energy tolerance for DRC

set nE=0`grep -n "SQRT(AMU)" $1 | tail -1 | cut -d: -f1 | awk '{ print $1+1 }'`
set E=`sed -n -e "$nE p" $1 | awk '{ print $8 }'`
set nV=0`grep -n "VEL(1)=" $1 | tail -1 | cut -d: -f1 | awk '{ print $1+3 }'`
set V=`sed -n -e "$nV p" $1 | awk '{ print $3 }'`

set ierr=0
set Eerr=`$chkabs $E $E0 $tolE0`
if($status != 0) set ierr=1 
set Verr=`$chkabs $V $V0 $tolV`
if($status != 0) set ierr=1
echo -n "Eerr=$Eerr Verr=$Verr. "
exit $ierr 
