#!/bin/csh
set Ea0=-75.010111355
set Eb0=-74.394581939
set Da0=0.392614
set Db0=0.368205
# D are not exactly same as normal dipole

set Ea=`grep "STATE #    1" $1 | awk '{ print $6 }'`0
set Eb=`grep "STATE #    2" $1 | awk '{ print $6 }'`0
set Da=`grep "E[*]BOHR" $1 | head -2 | tail -1 | awk '{ print $7 }'`0
set Db=`grep "E[/]BOHR" $1 | head -2 | tail -1 | awk '{ print $8 }'`0
set ierr=0
set Eaerr=`$chkabs $Ea $Ea0 $tolE`
if($status != 0) set ierr=1 
set Eberr=`$chkabs $Eb $Eb0 $tolE`
if($status != 0) set ierr=1 
set Daerr=`$chkabs $Da $Da0 $tolD`
if($status != 0) set ierr=1
set Dberr=`$chkabs $Db $Db0 $tolD`
if($status != 0) set ierr=1
echo -n "Eerr=$Eaerr+$Eberr Derr=$Daerr+$Dberr. "
exit $ierr 
