#!/bin/csh
set E0=-169.0085355753
set G0=0.008157643

set E=`grep "FINAL RHF" $1 | awk '{ print $5 }'`0
set G=`grep "RMS G" $1 | awk '{ print $4 }'`0
set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1 
set Gerr=`$chkabs $G $G0 $tolG`
if($status != 0) set ierr=1
echo -n "Eerr=$Eerr Gerr=$Gerr. "
exit $ierr 
