#!/bin/csh
set E0=-38.3334724789
set W0=1224.19
set I0=0.13317
set P0=0.53018

set E=`grep "FINAL GVB" $1 | awk '{ print $5 }'`0
set W=`grep "FREQUENCY:" $1 | tail -1 | awk '{ print $3 }'`0
set I=`grep "IR INTENSITY:" $1 | tail -1 | awk '{ print $4 }'`0
set P=`grep "MEAN ALPHA POL" $1 | awk '{ print $5 }'`0
set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1 
set Werr=`$chkabs $W $W0 $tolW`
if($status != 0) set ierr=1
set Ierr=`$chkabs $I $I0 $tolI`
if($status != 0) set ierr=1
set Perr=`$chkabs $P $P0 $tolP`
if($status != 0) set ierr=1
echo -n "Eerr=$Eerr Werr=$Werr Ierr=$Ierr Perr=$Perr. "
exit $ierr 
