#!/bin/csh
#
#     numerical gradient using open shell CR-CCL
#     what is checked is the type -D- energy,
#     along with the differentiated type -A- energy.
#
set E0=-92.4930167395
set G0=0.026601131

#   1st E is correct one, next two energies are for the NUMGRD
set E=`grep "CR-CCSD(T)_L E=" $1 | head -1 | awk '{ print $5 }'`0
#   1st gradient is in Cartesian space
set G=`grep "RMS G" $1 | head -1 | awk '{ print $4 }'`0

set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1 
set Gerr=`$chkabs $G $G0 $tolG`
if($status != 0) set ierr=1
echo -n "Eerr=$Eerr Gerr=$Gerr. "
exit $ierr 
