#!/bin/csh
set E0=-415.2660357291
set L0=28.389125

set E=`grep "FINAL RHF" $1 | awk '{ print $5 }'`0
set L=`grep "DIAGONAL SUM D" $1 | tail -1 | awk '{ print $4 }'`0
set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1 
set Lerr=`$chkabs $L $L0 $tolL`
if($status != 0) set ierr=1
echo -n "Eerr=$Eerr Lerr=$Lerr. "
exit $ierr 
