#!/bin/csh
set EXC0=8.474
set OSC0=0.094
set G0=0.112201641
set tol=0.001

#  check only the pi state, 5 lines after the title.
#  don't check transition dipole, that is mixed between two pi components

set nR=`grep -i -n "summary of tddft results" $1 | head -1 | cut -d: -f1`
@ nR = $nR + 5
set EXC=`sed -n -e "$nR p" $1 | awk '{ print $4 }'`
set OSC=`sed -n -e "$nR p" $1 | awk '{ print $8 }'`
set G=`grep "RMS G" $1 | tail -1 | awk '{ print $4 }'`0

set ierr=0
set EXCerr=`$chkabs $EXC $EXC0 $tol`
if($status != 0) set ierr=1
set OSCerr=`$chkabs $OSC $OSC0 $tol`
if($status != 0) set ierr=1
set Gerr=`$chkabs $G $G0 $tolG`
if($status != 0) set ierr=1
echo -n "EXCerr=$EXCerr eV, Gerr=$Gerr, OSCerr=$OSCerr. "
exit $ierr 
