#!/bin/csh
set E0=-39.2510351247
set W0=988.81
set I0=4.54558
set P0=2.04654

set E=`grep "FINAL GVB" $1 | awk '{ print $5 }'`0
set W=`grep "FREQUENCY:" $1 | head -2 | tail -1 | awk '{ print $6 }'`0
set I=`grep "IR INTENSITY:" $1 | head -2 | tail -1 | awk '{ print $7 }'`0
set P=`grep "MEAN ALPHA POL" $1 | awk '{ print $5 }'`0
set ierr=0
set Eerr=`$chkabs $E $E0 $tolE`
if($status != 0) set ierr=1 
set Werr=`$chkabs $W $W0 $tolW`
if($status != 0) set ierr=1
set Ierr=`$chkabs $I $I0 $tolI`
if($status != 0) set ierr=1
set Perr=`$chkabs $P $P0 $tolP`
if($status != 0) set ierr=1
echo -n "Eerr=$Eerr Werr=$Werr Ierr=$Ierr Perr=$Perr. "
exit $ierr 
