#!/bin/csh
#
#     exam44 is a divide and conquer MP2 single point energy run
#
set SCF0=-599.9687803934
set MP20=-600.7532099625

set SCF=`grep "FINAL"   $1 | tail -1 | awk '{ print $5 }'`0
set MP2=`grep "E(MP2)=" $1 | tail -1 | awk '{ print $2 }'`0

set ierr=0
set SCFerr=`$chkabs $SCF $SCF0 $tolE`
if($status != 0) set ierr=1 
set MP2err=`$chkabs $MP2 $MP20 $tolE`
if($status != 0) set ierr=1
echo -n "SCFerr=$SCFerr MP2err=$MP2err. "
exit $ierr 
